### ISSUE TITLE
Update readme to specify default value praxis

### ISSUE THREAD

**Issue by Syrou** [HelloCuriosity/model-forge#135]
Something that is not very clear while reading the documentation is what/if any default values are generated and how they behave for each different type.

**Comment by hopeman15** [comment]
@Syrou I started putting together a more detailed and organized documentation using docusaurus. You can see the current WIP [here](https://hellocuriosity.github.io/model-forge/docs/category/supported-types). I was wondering if you could take a look at how the supported types are currently described and get your opinion and feedback 🙌 Were you thinking about something like this, or is there something that you feel is still missing and/or unclear?

**Comment by Syrou** [comment]
@hopeman15 Looks pretty good to me!
